In [6]:
import numpy as np

In [7]:
np.array([1, 2, 3])

array([1, 2, 3])

In [8]:
np.array((([1,2,3], [4,5,6], [7,8,9])))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
ze= np.zeros([1,2,3])
ze

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.ones([2,2])
np.eye(1,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
ons=np.ones((5,6))
ons

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
x = np.arange(1,10,2)
x


array([1, 3, 5, 7, 9])

In [14]:
emp=np.empty(10)
emp=np.empty((5,20))
emp

array([[ 0.00000000e+000,  6.95189936e-310,  3.75489891e-321,
                     nan,  4.89559725e-307,  3.95252517e-322,
         0.00000000e+000,  4.89901943e-307,  2.92486862e-321,
         0.00000000e+000,  4.89988860e-307,  5.45448473e-321,
         0.00000000e+000,  9.04030243e-288,  2.77068867e-302,
         7.98410084e-321,  0.00000000e+000,  5.92255108e-283,
         1.72023233e-297,  2.82039254e-293],
       [ 9.03370143e-288,  1.67170408e-308,  3.88759808e-278,
         1.73918947e-244,  9.34203345e-313,  0.00000000e+000,
         1.66598936e-320,  2.12400268e-268,  0.00000000e+000,
         1.30433331e-320,  0.00000000e+000,  2.77069979e-302,
         1.52172219e-321,  2.08057643e-273,  1.10413590e-312,
         4.78294713e+035,  4.33789637e-321,  6.68854171e-311,
         0.00000000e+000,  0.00000000e+000],
       [ 2.38943636e-311, -4.22045589e+136,  1.26927072e-315,
         0.00000000e+000,  1.11253693e-307,  2.70161360e-225,
         0.00000000e+000,  0.00000000e+000

In [15]:
ls=np.linspace(1,10,20)
ls

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [16]:
ar=np.array([1,2,3,4,5,6,7,8,9,10])
ar
np.ndim(ar)

1

In [17]:
r=ar.reshape(2,5)
r

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
r.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
r.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
d3=ar.reshape(3,4)
d3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
d3=ar.reshape(3,2,2)
d3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [22]:
r.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [23]:
list1=[1,2,3,4]
list2=[1,2,3,4]
list1+list2


[1, 2, 3, 4, 1, 2, 3, 4]

In [24]:
list1=np.array([1,2,3,4])
list2=np.array([1,2,3,4])
list1+list2

array([2, 4, 6, 8])

In [25]:
list1=np.array([1,2,3,4])
list2=np.array([5,6,7,8])
list1*list2

array([ 5, 12, 21, 32])

In [26]:
np.dot(list1,list2)

np.int64(70)

In [27]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
r=ar.reshape(3,4)
r



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
r.min()

np.int64(1)

In [29]:
r.argmin()

np.int64(0)

In [30]:
np.sqrt(r)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [31]:
np.mean(r)

np.float64(6.5)

In [32]:
np.median(r)

np.float64(6.5)

In [33]:
stats.mode(r)

NameError: name 'stats' is not defined

In [ ]:
np.std(r)

np.float64(3.452052529534663)

In [ ]:
list1=[1,2,3,4]
list2=[5,6,7,8]
np.concatenate((list1,list2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.vstack((list1,list2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
a=np.array([ 1,2,3,4])
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

## indexing and slicing on 1D

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

np.int64(50)

In [54]:
arr[0]

np.int64(10)

In [55]:
arr[-1]

np.int64(50)

# slicing

In [45]:
arr[1:4]

array([20, 30, 40])

In [46]:
arr[:3]

array([10, 20, 30])

In [47]:
arr[2:]

array([30, 40, 50])

## indexing and slicing in 2D

In [60]:
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# indexing

In [61]:
arr2[1,1]

np.int64(5)

In [62]:
arr2[2,1]

np.int64(8)

# slicing

In [63]:
arr2[0, :]

array([1, 2, 3])

In [64]:
arr2[0:2 , 1:3]

array([[2, 3],
       [5, 6]])

# convert 1D to 3D and perfrom indexing and slicing

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8], [])
arr3d = arr1.reshape(2,2,2)
print(arr3d) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## indexing in 3D

In [ ]:
print(arr3d[0,0,0])  # 1st block, 1st row, 1st column → 1
print(arr3d[1,1,1])  # 2nd block, 2nd row, 2nd column → 8
print(arr3d[])

1
8


# Slicing in 3D
# arr3d[block_slice, row_slice, column_slice]

In [76]:
print(arr3d[0:1, 0:2, 0:2])

[[[1 2]
  [3 4]]]


In [77]:
# Minimun value
np.min((arr3d))

np.int64(1)

In [79]:
# index of minimum value
np.argmin((arr3d))

np.int64(0)

In [78]:
# maximum value
np.max((arr3d))

np.int64(8)

In [ ]:
# index of maximum value
np.argmax((arr3d))

np.int64(7)

In [81]:
# mean 
np.mean((arr3d))

np.float64(4.5)

In [82]:
# median
np.median((arr3d))

np.float64(4.5)

In [83]:
np.transpose(arr3d, axes=((1,0,2)))

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [113]:
# Step 1: Create a 3D array with 5 blocks, 5 rows, 10 columns filled with random integers 0-99
arr3d = np.random.randint(0, 100, size=(5, 5, 10))
print(arr3d)
# Step 2: Access the element at block 2, row 3, column 5 (Python indexing starts at 0)

arr3d = np.random.randint(0, 100, size=(5,5,10))

# Step 3: Print the result
print("Random element at block 2, row 3, column 5:", random_number)

[[[15 13 83  9 21 88  6 12 19 82]
  [20  1 26 97 33 98 40 55  7 84]
  [36 19 16  1 20 78 69 94 75 51]
  [57 97  1 83 83 88 87 75 38 13]
  [75 30 75 52 45 75 67 82 55 52]]

 [[61 75 65 21 35 31 42  4 85 20]
  [19 31 45 20 32 50 70 99 78 63]
  [37  6 62 32  4 43 65 57 51 33]
  [42 85  3 42 41 82 75 82  5 56]
  [ 3 21 52 38  0 10  5 69 57 35]]

 [[60 51 30  3 64 85 53 39 38 34]
  [79 60 91 14 13  4 75 45 66 38]
  [89 66 74 56 92 56 13 91 38 44]
  [24 47 27 89 72 17 20 37 36 19]
  [51 78 95 90 75 64 79 74 37 16]]

 [[29 24 60 12 88 90 81 92 38 30]
  [45 21  5 52 63 28 11 42 74 13]
  [71 84 71 14  0 81 58 39 59 54]
  [ 1 48  2 38 52 95 64 45  0 68]
  [34 68 37  5 80 94 93  7 85 60]]

 [[92 11 48 37 85  5 22 53 84 70]
  [99 53 35 50 25 48 12 72 10 75]
  [87 79 97 47 53 24 55 34 51 71]
  [82 89 96 22 79  6 19 62 88 31]
  [57 39  6 39 20 86 62 60 38 88]]]
Random element at block 2, row 3, column 5: 97


In [ ]:
# Step 1: Create a 3D array (5 blocks, 5 rows, 10 columns) with random integers 0-99
arr3d = np.random.randint(0, 100, size=(5, 5, 10))
print(arr3d)

# Step 2: Check total number of elements
total_elements = arr3d.size
print("Total elements in the array:", total_elements)  # should print 250

# Step 3: Access a specific element (block 2, row 3, column 5)
random_number = arr3d[2, 4, 7]
print("Element at block 2, row 3, column 5:", random_number)

[[[60 79 63 78 74 78 58 25 13 24]
  [83 91 32 10 95 94 29 94 37 39]
  [ 9 52 25 94 11 71 25 63 13  8]
  [20 16  1  5 28  8 44 22 21 89]
  [80 16 18 27 85 28 57  9 37 25]]

 [[51 67 91 79 21 78 23 57 82 34]
  [58 92 95 79 55 95 49 44 29  4]
  [ 0 87 72 32 61  4 49 97 82 42]
  [95 94 16 68 58 16 32 95 50 16]
  [63 30 87 86 99 21 74 70 85  9]]

 [[45 43  9 32 69 70 84 85 30 48]
  [32 44 13 85 40 98 41 61 57 35]
  [ 7 13 54  3  5 40 68  0 69 75]
  [49 16 37 48 65 98 40 36 88 49]
  [ 1 17 19 14 15 76  7 97 80 89]]

 [[12 86 36 51 87 65 24 48 78 90]
  [46 80 81 84 32 21 36 70 71 15]
  [76 40 25 85 86 74 51 19  7 25]
  [71 20 60 59  7 26  3 20 28  5]
  [47 46  6 68 72 83 55 13 22 20]]

 [[14 86 98 45 18  3 58 40 47 25]
  [85 14  5 50 88 54  2  2 49 46]
  [ 6 15 55 34 58 10 88 54 67 96]
  [42 32 80 62 38  9 33 33 38  9]
  [ 9 57  3 20  2  9 65  4 40 95]]]
Total elements in the array: 250
Element at block 2, row 3, column 5: 97
