## 04-03-2026
# half work is in note book 03-03-2026

In [1]:
import numpy as np

In [ ]:
# array() function is used to creat array
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [21]:
# using list[] to creat array
arrr=np.array([1,2,3])
arrr

array([1, 2, 3])

In [7]:
# using tuple() to creat array
ar= np.array((1,2,3,4))
ar

array([1, 2, 3, 4])

In [ ]:
# To convert list into array use array () function
list=[1,2,3,4]
arr=np.array(list)
arr

array([1, 2, 3, 4])

In [26]:
# To find type of array use type(name of array)
a=np.array(([5,4,3],[1,2,3]))
type(a)

numpy.ndarray

In [27]:
q=np.array([5,4,3])
type(q)

numpy.ndarray

In [37]:
# dytype is used to find data type of array
arr=np.array(([1,2,3,4], [5,6,7,8]))
arr.dtype

dtype('int64')

## Checking how many dimensions the arrays have

In [40]:
# To find dimenshion of array
w=np.array([1,2,3,4,5]) 
print(w.ndim)
e=np.array(([3,4,5],[3,8,7]))
print(e.ndim)

1
2


In [ ]:
# arrayname.ndim is used to find dimensions of array
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Reshape 

In [ ]:
# reshape
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
r=ar.reshape(3,4)
r

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# converting data type from existing array

In [45]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


## Numpy ONES functions

In [28]:
ons=np.array([1,2,3,4,5])
ons

array([1, 2, 3, 4, 5])

In [46]:
onr=np.ones(5)
print(onr)

[1. 1. 1. 1. 1.]


In [55]:
np.ones([2,2], dtype=int)

array([[1, 1],
       [1, 1]])

In [54]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])