## 05-03-2026

In [1]:
import numpy as np

## Broadcasting method on 2D
# multiplying 2D array with a number

In [23]:
# multiplying 2D array with a number
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)

result = arr * 2

print(result)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


#  multiplying 2D array with 1D array

In [24]:
# multiplying 2D array with 1D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)
b = np.array([10, 20, 30])

result = arr * b
print(result)

[[1 2 3]
 [4 5 6]]
[[ 10  40  90]
 [ 40 100 180]]


In [26]:
# multiply 2D with 1D

A = np.array([[2, 5, 7],
              [3, 5, 8]])
B = np.array([[10, 10, 10]])
result = A * B
print(result)

[[20 50 70]
 [30 50 80]]


In [25]:
# multiply 2D with Column
A = np.array([[3,4,5],
              [1,2,3]])
B = np.array([[4],
              [5]])
result = A * B
print(result)

[[12 16 20]
 [ 5 10 15]]


In [35]:
A = np.array([[3,4,5],
              [1,2,3]])
print(A)
B=np.array(([3,4,5], 
             [3,2,1]))
print(B)
result=A*B
print(result)

[[3 4 5]
 [1 2 3]]
[[3 4 5]
 [3 2 1]]
[[ 9 16 25]
 [ 3  4  3]]
